function PrivacyPolicy() {
    const containerStyle = {
        maxWidth: '800px',
        margin: 'auto',
        fontFamily: "Google Sans, Roboto, Arial, sans-serif",
        padding:"10px",
         lineHeight: "1.25rem",
         letterSpacing: ".0178571429em",
         fontSize: ".91rem",
         color: "rgb(95, 99, 104)",
         fontWeight: "550",
    };

    const headingStyle = {
        fontSize: '24px',
        fontWeight: 'bold',
        marginBottom: '10px'
    };

    const linkStyle = {
        color: '#007bff',
        textDecoration: 'underline'
    };

    return (
        <div style={containerStyle}>
            <h1 style={headingStyle}>Privacy Policy</h1>
            <p><strong>Last updated:</strong> June 24, 2024</p>
            <p>This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of your information when you use the service and tells you about your privacy rights and how the law protects you.</p>
            <p>We use your personal data to provide and improve the service. By using the service, you agree to the collection and use of information in accordance with this privacy policy.</p>
            
            <h2 style={headingStyle}>Interpretation and Definitions</h2>
            
            <h3 style={headingStyle}>Interpretation</h3>
            <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            
            <h3 style={headingStyle}>Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
            <ul>
                <li><strong>Account:</strong> A unique account created for you to access our service or parts of our service.</li>
                <li><strong>Affiliate:</strong> An entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.</li>
                <li><strong>Company:</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to HD Downloader.</li>
                <li><strong>Cookies:</strong> Small files that are placed on your computer, mobile device, or any other device by a website, containing the details of your browsing history on that website among its many uses.</li>
                <li><strong>Country:</strong> Refers to Telangana, India.</li>
                <li><strong>Device:</strong> Any device that can access the service such as a computer, a cellphone, or a digital tablet.</li>
                <li><strong>Personal Data:</strong> Any information that relates to an identified or identifiable individual.</li>
                <li><strong>Service:</strong> Refers to the website.</li>
                <li><strong>Service Provider:</strong> Any natural or legal person who processes the data on behalf of the company. It refers to third-party companies or individuals employed by the company to facilitate the service, to provide the service on behalf of the company, to perform services related to the service, or to assist the company in analyzing how the service is used.</li>
                <li><strong>Third-party Social Media Service:</strong> Any website or any social network website through which a user can log in or create an account to use the service.</li>
                <li><strong>Usage Data:</strong> Data collected automatically, either generated by the use of the service or from the service infrastructure itself (for example, the duration of a page visit).</li>
                <li><strong>Website:</strong> Refers to HD Downloader, accessible from <a href="http://www.hdyoutube.in" target="_blank" rel="noopener noreferrer">http://www.hdyoutube.in</a></li>
                <li><strong>You:</strong> The individual accessing or using the service, or the company, or other legal entity on behalf of which such individual is accessing or using the service, as applicable.</li>
            </ul>

            <h2 style={headingStyle}>Collecting and Using Your Personal Data</h2>

            <h3 style={headingStyle}>Types of Data Collected</h3>

            <h4 style={headingStyle}>Personal Data</h4>
            <p>While using our service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:</p>
            <ul>
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Usage data</li>
            </ul>

            <h4 style={headingStyle}>Usage Data</h4>
            <p>Usage data is collected automatically when using the service. Usage data may include information such as your device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers, and other diagnostic data. When you access the service by or through a mobile device, we may collect certain information automatically, including, but not limited to, the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers, and other diagnostic data. We may also collect information that your browser sends whenever you visit our service or when you access the service by or through a mobile device.</p>

            <h4 style={headingStyle}>Information from Third-Party Social Media Services</h4>
            <p>The company allows you to create an account and log in to use the service through the following third-party social media services:</p>
            <ul>
                <li>Google</li>
                <li>Facebook</li>
                <li>Instagram</li>
                <li>Twitter</li>
                <li>LinkedIn</li>
            </ul>
            <p>If you decide to register through or otherwise grant us access to a third-party social media service, we may collect personal data that is already associated with your third-party social media service's account, such as your name, your email address, your activities, or your contact list associated with that account. You may also have the option of sharing additional information with the company through your third-party social media service's account. If you choose to provide such information and personal data, during registration or otherwise, you are giving the company permission to use, share, and store it in a manner consistent with this privacy policy.</p>

            <h4 style={headingStyle}>Tracking Technologies and Cookies</h4>
            <p>We use cookies and similar tracking technologies to track the activity on our service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze our service. The technologies we use may include:</p>
            <ul>
                <li><strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on your device. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some parts of our service. Unless you have adjusted your browser setting so that it will refuse cookies, our service may use cookies.</li>
                <li><strong>Web Beacons:</strong> Certain sections of our service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
            </ul>
            <p>Cookies can be "persistent" or "session" cookies. Persistent cookies remain on your personal computer or mobile device when you go offline, while session cookies are deleted as soon as you close your web browser. You can learn more about cookies on the <a href="https://www.termsfeed.com/blog/cookies/#What_Are_Cookies" target="_blank" rel="noopener noreferrer" style={linkStyle}>TermsFeed website</a>.</p>
            <p>We use both session and persistent cookies for the purposes set out below:</p>
            <ul>
                <li>
                    <p><strong>Necessary / Essential Cookies</strong></p>
                    <p>Type: Session Cookies</p>
                    <p>Administered by: Us</p>
                    <p>Purpose: These cookies are essential to provide you with services available through the website and to enable you to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these cookies, the services that you have asked for cannot be provided, and we only use these cookies to provide you with those services.</p>
                </li>
                <li>
                    <p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
                    <p>Type: Persistent Cookies</p>
                    <p>Administered by: Us</p>
                    <p>Purpose: These cookies identify if users have accepted the use of cookies on the website.</p>
                </li>
                <li>
                    <p><strong>Functionality Cookies</strong></p>
                    <p>Type: Persistent Cookies</p>
                    <p>Administered by: Us</p>
                    <p>Purpose: These cookies allow us to remember choices you make when you use the website, such as remembering your login details or language preference. The purpose of these cookies is to provide you with a more personal experience and to avoid you having to re-enter your preferences every time you use the website.</p>
                </li>
            </ul>
            
            <h2 style={headingStyle}>Use of Your Personal Data</h2>
            <p>The company may use personal data for the following purposes:</p>
            <ul>
                <li>To provide and maintain our service, including to monitor the usage of our service.</li>
                <li>To manage your account: to manage your registration as a user of the service. The personal data you provide can give you access to different functionalities of the service that are available to you as a registered user.</li>
                <li>To contact you: To contact you by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products, or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
                <li>To manage your requests: To attend and manage your requests to us.</li>
                <li>For business transfers: We may use your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which personal information held by us about our service users is among the assets transferred.</li>
                <li>For other purposes: We may use your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and evaluating and improving our service, products, services, marketing, and your experience.</li>
            </ul>

            <h2 style={headingStyle}>Retention of Your Personal Data</h2>
            <p>The company will retain your personal data only for as long as is necessary for the purposes set out in this privacy policy. We will retain and use your personal data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
            <p>The company will also retain usage data for internal analysis purposes. Usage data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our service, or we are legally obligated to retain this data for longer periods.</p>

            <h2 style={headingStyle}>Transfer of Your Personal Data</h2>
            <p>Your information, including personal data, is processed at the company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>
            <p>Your consent to this privacy policy followed by your submission of such information represents your agreement to that transfer.</p>
            <p>The company will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this privacy policy and no transfer of your personal data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>

            <h2 style={headingStyle}>Disclosure of Your Personal Data</h2>
            <h3 style={headingStyle}>Business Transactions</h3>
            <p>If the company is involved in a merger, acquisition, or asset sale, your personal data may be transferred. We will provide notice before your personal data is transferred and becomes subject to a different privacy policy.</p>

            <h3 style={headingStyle}>Law Enforcement</h3>
            <p>Under certain circumstances, the company may be required to disclose your personal data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>

            <h3 style={headingStyle}>Other Legal Requirements</h3>
            <p>The company may disclose your personal data in the good faith belief that such action is necessary to:</p>
            <ul>
                <li>Comply with a legal obligation</li>
                <li>Protect and defend the rights or property of the company</li>
                <li>Prevent or investigate possible wrongdoing in connection with the service</li>
                <li>Protect the personal safety of users of the service or the public</li>
                <li>Protect against legal liability</li>
            </ul>

            <h2 style={headingStyle}>Security of Your Personal Data</h2>
            <p>The security of your personal data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your personal data, we cannot guarantee its absolute security.</p>

            <h2 style={headingStyle}>Children's Privacy</h2>
            <p>Our service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your child has provided us with personal data, please contact us. If we become aware that we have collected personal data from anyone under the age of 13 without verification of parental consent, we take steps to remove that information from our servers.</p>

            <h2 style={headingStyle}>Links to Other Websites</h2>
            <p>Our service may contain links to other websites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the privacy policy of every site you visit.</p>
            <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

            <h2 style={headingStyle}>Changes to This Privacy Policy</h2>
            <p>We may update our privacy policy from time to time. We will notify you of any changes by posting the new privacy policy on this page.</p>
            <p>You are advised to review this privacy policy periodically for any changes. Changes to this privacy policy are effective when they are posted on this page.</p>

            <h2 style={headingStyle}>Contact Us</h2>
            <p>If you have any questions about this privacy policy, please contact us:</p>
            <ul>
                <li>By email: <a href="mailto:contact@hdyoutube.in" style={linkStyle}>contact@hdyoutube.in</a></li>
                <li>By visiting this page on our website: <a href="http://www.hdyoutube.in/contact" target="_blank" rel="noopener noreferrer" style={linkStyle}>http://www.hdyoutube.in/contact</a></li>
            </ul>
        </div>
    );
}

export default PrivacyPolicy;
